name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: Demo-EKS
  ECR_REPOSITORY: demo-app

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --name $EKS_CLUSTER_NAME \
            --region $AWS_REGION

      - name: Get AWS account ID
        id: account
        run: |
          echo "account_id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      - name: Update deployment image
        run: |
          kubectl -n demo set image deployment/demo-app \
            demo-app=${{ steps.account.outputs.account_id }}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${{ github.event.workflow_run.head_sha }}

      - name: Wait for rollout
        run: |
          kubectl -n demo rollout status deployment/demo-app